// Code generated by hertz generator.

package casbin

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upgradeorokMw() []app.HandlerFunc {
	// your code...
	return nil
}
