// Code generated by hertz generator.

package ai

import (
	"github.com/MyGoFor/E-commerce/app/frontend/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.Auth()}
}

func _tocartMw() []app.HandlerFunc {
	// your code...
	return nil
}
