// Code generated by Kitex v0.9.1. DO NOT EDIT.

package upgradeservice

import (
	"context"
	upgrade "github.com/MyGoFor/E-commerce/rpc_gen/kitex_gen/upgrade"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Upgrade(ctx context.Context, Req *upgrade.UpgradeReq, callOptions ...callopt.Option) (r *upgrade.Empty, err error)
	Ok(ctx context.Context, Req *upgrade.OkReq, callOptions ...callopt.Option) (r *upgrade.Empty, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUpgradeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUpgradeServiceClient struct {
	*kClient
}

func (p *kUpgradeServiceClient) Upgrade(ctx context.Context, Req *upgrade.UpgradeReq, callOptions ...callopt.Option) (r *upgrade.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Upgrade(ctx, Req)
}

func (p *kUpgradeServiceClient) Ok(ctx context.Context, Req *upgrade.OkReq, callOptions ...callopt.Option) (r *upgrade.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Ok(ctx, Req)
}
