// Code generated by Kitex v0.9.1. DO NOT EDIT.

package upgradeservice

import (
	"context"
	"errors"
	upgrade "github.com/MyGoFor/E-commerce/rpc_gen/kitex_gen/upgrade"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Upgrade": kitex.NewMethodInfo(
		upgradeHandler,
		newUpgradeArgs,
		newUpgradeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Ok": kitex.NewMethodInfo(
		okHandler,
		newOkArgs,
		newOkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	upgradeServiceServiceInfo                = NewServiceInfo()
	upgradeServiceServiceInfoForClient       = NewServiceInfoForClient()
	upgradeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return upgradeServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return upgradeServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return upgradeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UpgradeService"
	handlerType := (*upgrade.UpgradeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "upgrade",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func upgradeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(upgrade.UpgradeReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(upgrade.UpgradeService).Upgrade(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpgradeArgs:
		success, err := handler.(upgrade.UpgradeService).Upgrade(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpgradeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpgradeArgs() interface{} {
	return &UpgradeArgs{}
}

func newUpgradeResult() interface{} {
	return &UpgradeResult{}
}

type UpgradeArgs struct {
	Req *upgrade.UpgradeReq
}

func (p *UpgradeArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(upgrade.UpgradeReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpgradeArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpgradeArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpgradeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpgradeArgs) Unmarshal(in []byte) error {
	msg := new(upgrade.UpgradeReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpgradeArgs_Req_DEFAULT *upgrade.UpgradeReq

func (p *UpgradeArgs) GetReq() *upgrade.UpgradeReq {
	if !p.IsSetReq() {
		return UpgradeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpgradeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpgradeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpgradeResult struct {
	Success *upgrade.Empty
}

var UpgradeResult_Success_DEFAULT *upgrade.Empty

func (p *UpgradeResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(upgrade.Empty)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpgradeResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpgradeResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpgradeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpgradeResult) Unmarshal(in []byte) error {
	msg := new(upgrade.Empty)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpgradeResult) GetSuccess() *upgrade.Empty {
	if !p.IsSetSuccess() {
		return UpgradeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpgradeResult) SetSuccess(x interface{}) {
	p.Success = x.(*upgrade.Empty)
}

func (p *UpgradeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpgradeResult) GetResult() interface{} {
	return p.Success
}

func okHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(upgrade.OkReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(upgrade.UpgradeService).Ok(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *OkArgs:
		success, err := handler.(upgrade.UpgradeService).Ok(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*OkResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newOkArgs() interface{} {
	return &OkArgs{}
}

func newOkResult() interface{} {
	return &OkResult{}
}

type OkArgs struct {
	Req *upgrade.OkReq
}

func (p *OkArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(upgrade.OkReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *OkArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *OkArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *OkArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *OkArgs) Unmarshal(in []byte) error {
	msg := new(upgrade.OkReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var OkArgs_Req_DEFAULT *upgrade.OkReq

func (p *OkArgs) GetReq() *upgrade.OkReq {
	if !p.IsSetReq() {
		return OkArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *OkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OkArgs) GetFirstArgument() interface{} {
	return p.Req
}

type OkResult struct {
	Success *upgrade.Empty
}

var OkResult_Success_DEFAULT *upgrade.Empty

func (p *OkResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(upgrade.Empty)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *OkResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *OkResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *OkResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *OkResult) Unmarshal(in []byte) error {
	msg := new(upgrade.Empty)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *OkResult) GetSuccess() *upgrade.Empty {
	if !p.IsSetSuccess() {
		return OkResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OkResult) SetSuccess(x interface{}) {
	p.Success = x.(*upgrade.Empty)
}

func (p *OkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OkResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Upgrade(ctx context.Context, Req *upgrade.UpgradeReq) (r *upgrade.Empty, err error) {
	var _args UpgradeArgs
	_args.Req = Req
	var _result UpgradeResult
	if err = p.c.Call(ctx, "Upgrade", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Ok(ctx context.Context, Req *upgrade.OkReq) (r *upgrade.Empty, err error) {
	var _args OkArgs
	_args.Req = Req
	var _result OkResult
	if err = p.c.Call(ctx, "Ok", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
